name: Upload File to Linux Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OpenSSH
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
          Start-Service ssh-agent

      - name: Configure SSH Agent
        run: |
          ssh-add - <<<"${{ secrets.SERVER_PRIVATE_KEY }}"

      - name: Upload file via SCP
        run: |
          scp -o StrictHostKeyChecking=no -i $env:SSH_AUTH_SOCK build ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_PATH }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
