name: Upload File to Linux Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Git
        run: |
          choco install git -y

      - name: Set up Git Bash
        run: |
          echo 'export PATH="/usr/bin:$PATH"' >> $GITHUB_ENV

      - name: Upload file via SCP
        run: |
          export SSHPASS="${{ secrets.SSH_PASSWORD }}"
          scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} path/to/local/file ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_PATH }}
